### ISSUE TITLE
I can´t hear anything on Android

### ISSUE THREAD

**Issue by daviddomkar** [oxygine/oxygine-sound#7]
Hello, recently I included oxygine sound to my project, everything is working fine when built on windows, but on Android I can´t hear any sound. Also I have something like an error in my logcat.

> 02-21 00:41:23.890 18675-18749/com.playpilgrim.game D/SDL: 028 DebugActor::initialize
02-21 00:41:23.947 18675-18749/com.playpilgrim.game I/OpenAL_SLES: opensles_open_playback pDevice=0x7f67d9f5c0, deviceName=opensles
02-21 00:41:23.948 18675-18749/com.playpilgrim.game E/linker: library "/system/lib/libOpenSLES.so" ("/system/lib/libOpenSLES.so") needed or dlopened by "/data/app/com.playpilgrim.game-2/lib/arm64/libmain.so" is not accessible for the namespace: [name="classloader-namespace", ld_library_paths="", default_library_paths="/data/app/com.playpilgrim.game-2/lib/arm64:/data/app/com.playpilgrim.game-2/base.apk!/lib/arm64-v8a", permitted_paths="/data:/mnt/expand:/data/data/com.playpilgrim.game"]
02-21 00:41:23.949 18675-18749/com.playpilgrim.game I/OpenAL_SLES: OpenSLES could not be loaded.
02-21 00:41:23.949 18675-18749/com.playpilgrim.game D/SDL: 087 error: Assert! 0 in D:/Projects/Pilgrim/proj.android/jni/src/../../../oxygine-framework-with-sdl/oxygine-sound/src/sound/oal/SoundSystemOAL.cpp:57
02-21 00:41:23.949 18675-18749/com.playpilgrim.game D/SDL: 087 error: can't create SoundSystemOAL
02-21 00:41:23.954 18675-18675/com.playpilgrim.game V/SDL: onWindowFocusChanged(): true

Any solution?

**Comment by frankinshtein** [comment]
OpenSLES could not be loaded.  (OpenSLES used by openal)
What android device?

**Comment by frankinshtein** [comment]
Are you building arm64 game? try only arm7a

**Comment by daviddomkar** [comment]
Android device is Xiaomi Mi Max Helium. Also, it behaves same on all ABIs.

**Comment by frankinshtein** [comment]
are you sure that your APK didn't have previous arm8 binaries when you tested arm7?

**Comment by daviddomkar** [comment]
That was it. I cleaned the project, rebuilt it just for arm7a and it started working. However I need to use arm8 as well as a target. Is it possible to build it for arm64 correctly? And how?

**Comment by frankinshtein** [comment]
yes, switch all your oxygine-*  repositories to ox-move branch
it is development branch, new version of oxygine.  
and it will work out of box

**Comment by daviddomkar** [comment]
It looks I will also have to refractor my project little bit. Anyway, thank you for helping me figure it out. I'll try to switch to that dev branch.

**Comment by frankinshtein** [comment]
yes, you will have to make some minor changes related with "includes"
